layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 11
  exclude:
    archived: false
    forks: false
    projects:
      ["personal-website",
      "AP-CS",
      "cs50",]
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Cloud Computing
    web_url: https://github.com/topics/cloud-computing
    image_url: https://pronto-core-cdn.prontomarketing.com/2/wp-content/uploads/sites/1614/2019/07/21743298_1406722539365107_4308832733562613967_n.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://static.thenounproject.com/png/1870030-200.png

  - name: Internet of Things(IoT)
    web_url: https://github.com/topics/internet-of-things
    image_url: https://technolag.com/wp-content/uploads/2018/11/internet-of-things-534x462.jpg